name: Build jobs

on: [push, pull_request]

jobs:
  build:
    name: Build jobs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Build jobs
        run: yarn build:jobs