name: Update case data

on:
  schedule:
    - cron: '*/15 7-13 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '15'
    
      - name: Checkout master
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn

      - name: Fetch data
        run: yarn sync

      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coauthor_name: Marton Lederer
          coauthor_email: marton@lederer.hu
          message: Update case data