name: Validate

on: [push, pull_request]

jobs:
  svelte-check:
    name: Svelte-check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install yarn
        run: npm i -g yarn

      - name: Install dependencies
        run: yarn

      - name: Validate
        run: yarn validate